# ===============================
# APP
# ===============================
quarkus.application.name=curriculo-app-quarkus
quarkus.http.port=8080

# ===============================
# LOG
# ===============================
quarkus.log.level=INFO

# ===============================
# DEV PROFILE
# ===============================
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:resume;DB_CLOSE_DELAY=-1
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=sa

%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.format-sql=true

%dev.quarkus.devservices.enabled=false
