# ===============================
# APP
# ===============================
quarkus.application.name=curriculo-app-quarkus
quarkus.http.port=8080

# ===============================
# PROFILE
# ===============================
quarkus.profile=dev

# ===============================
# DATASOURCE - H2 (DEV)
# ===============================
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/curriculo-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.max-size=16

# ===============================
# HIBERNATE ORM
# ===============================
# NUNCA use drop-and-create se você quer testar POST + GET
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# ===============================
# LOG
# ===============================
quarkus.log.level=INFO
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.type.descriptor.sql".level=TRACE

# ===============================
# DEV MODE
# ===========================
