# ===============================
# APP
# ===============================
quarkus.application.name=curriculo-app-quarkus
quarkus.http.port=8080

# ===============================
# LOG
# ===============================
quarkus.log.level=INFO

# ===============================
# DEV PROFILE
# ===============================
# Datasource persistente
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/curriculo-db
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# Hibernate ORM (DEV)
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true


%dev.quarkus.devservices.enabled=false

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true

quarkus.log.category."org.hibernate.SQL".level=DEBUG

